"""
TradeX – Token Budget Manager  (v2 – Automatic Rolling Memory)
==============================================================

ROOT CAUSE OF THE ORIGINAL ERROR
----------------------------------
The previous retry path in _call_groq_with_budget() correctly caught 413s and
rebuilt a trimmed payload, but then raised HTTP 503 with:

    "The conversation history is too long for the current Groq plan.
     Please start a new session or delete this session's history …"

…if that ONE retry also failed.  The retry itself was sometimes still too
large because:

  1. `build_summary_message()` was only called on the non-system tail of the
     *already-trimmed* messages – so if the session's RAW history (stored in
     _SESSION_STORE) was still huge, the next request would hit 413 again
     immediately, the single retry would blow up again, and the 503 was raised.

  2. The in-memory session store was never persistently summarised.  Every
     call reconstructed `current_messages = list(_SESSION_STORE[sid])` from the
     full history.  Even if one request trimmed for its own call, the *store*
     remained bloated for the next call.

  3. No feedback loop: after a 413-retry the trimmed messages were NOT written
     back to _SESSION_STORE, so the same oversized history would cause the
     same error next turn.

ARCHITECTURE OF THE FIX
-------------------------

                   ┌─────────────────────────────────────────────┐
                   │             _SESSION_STORE[sid]              │
                   │                                              │
                   │  system_msg (always kept)                    │
                   │  ┌──────────────────────────────────┐        │
                   │  │  long_term_summary  (role=user)  │  ←──┐  │
                   │  │  [auto-generated by this module] │     │  │
                   │  └──────────────────────────────────┘     │  │
                   │  recent_messages  (last N turns)           │  │
                   └────────────────────────┬────────────────┬──┘  │
                                            │                │     │
                             exceeds SOFT   │                │     │
                               THRESHOLD    ▼                │     │
                                  compress_session() ────────┘     │
                                  (writes summary back)            │
                                                                   │
                      _call_groq_with_budget()                     │
                         pre-flight trim                           │
                         call Groq                                 │
                         413? → emergency_compress() ─────────────┘

KEY CHANGES vs v1
------------------
| Problem                                    | Fix                                        |
|--------------------------------------------|--------------------------------------------|
| 503 raised after one failed retry          | 3-stage fallback; never raises 503         |
| Session store stays bloated forever        | compress_session() mutates store in place  |
| Summary only on 413 (reactive)             | Proactive summarisation at SOFT_THRESHOLD  |
| Summary built from trimmed msgs (stale)    | Summary built from FULL session history    |
| Single retry with fixed tail=3 messages    | Adaptive tail size + 3 progressive retries |
| No deduplication of tool results           | deduplicate_tool_results() removes repeats |

Groq free-tier limits
----------------------
  TPM (tokens per minute):  12 000
  Target input ceiling:      7 500  (leaves 4 500 for output + headroom)
  Soft compression trigger:  6 000  (compress before we hit the ceiling)
  Hard emergency ceiling:    5 000  (used in last-resort retry)
"""

from __future__ import annotations

import json
import logging
from typing import Any

logger = logging.getLogger("tradex.ai.token_budget")

# ---------------------------------------------------------------------------
# Token budget constants
# ---------------------------------------------------------------------------

# Hard ceiling for input tokens sent to Groq (free tier: 12 000 TPM total).
# We reserve ~4 500 for output + framing overhead.
TOKEN_BUDGET: int = 7_500

# When the session store reaches this token count we proactively summarise.
# This prevents the store from growing to the point where even a fresh request
# exceeds the hard ceiling.
SOFT_COMPRESSION_THRESHOLD: int = 6_000

# Emergency ceiling used during 413 retry path (absolute minimum).
EMERGENCY_TOKEN_BUDGET: int = 4_500

# How many recent messages to ALWAYS keep (never summarised away).
# Covers: last user turn + assistant tool-call msg + tool result + final reply
# = 4 messages minimum.  We keep 6 to preserve one full extra exchange.
_MIN_RECENT_MESSAGES: int = 6

# How many items from a "heavy" array field to keep in compressed tool results.
_MAX_ARRAY_ITEMS: int = 3   # was 5 in v1; tighter = safer

# Conservative chars-per-token ratio (mixed JSON/English; ±15% accuracy).
_CHARS_PER_TOKEN: float = 3.8

# Tool results older than this many rounds are eligible for deep compression.
_STALE_TOOL_ROUNDS: int = 2


# ===========================================================================
# Token estimation
# ===========================================================================

def estimate_tokens(text: str) -> int:
    """
    Fast ≈token count via character heuristic.
    Accuracy: ±15 % – good enough for budget gating.
    """
    if not text:
        return 0
    return max(1, int(len(text) / _CHARS_PER_TOKEN))


def estimate_messages_tokens(messages: list[dict[str, Any]]) -> int:
    """
    Estimate total token count for an OpenAI-format messages list.
    Accounts for content, tool_calls, and per-message overhead (~4 tokens).
    """
    total = 0
    for msg in messages:
        total += 4  # role + framing overhead
        content = msg.get("content")
        if isinstance(content, str):
            total += estimate_tokens(content)
        tool_calls = msg.get("tool_calls")
        if tool_calls:
            total += estimate_tokens(json.dumps(tool_calls, default=str))
    return total


# ===========================================================================
# Tool result compression
# ===========================================================================

# Fields known to carry large arrays. Trimmed aggressively in history copies.
_HEAVY_ARRAY_KEYS: frozenset[str] = frozenset({
    "trades", "win_loss_chart", "pnl_per_trade", "equity_curve", "candles",
    "ohlcv", "rows", "data", "posts", "results", "hourly_sentiment",
    "hourly", "per_post", "items", "records", "entries",
})


def compress_tool_result(tool_name: str, data: dict[str, Any]) -> dict[str, Any]:
    """
    Return a token-reduced copy of a tool result dict for storage in history.

    Heavy array fields are truncated to _MAX_ARRAY_ITEMS entries.  A
    `__<key>_total__` sibling key tells the model the original count so it
    can still reason about the full dataset.

    The UNCOMPRESSED original is always returned to the UI via
    AIChatResponse.data – only the history copy is compressed.
    """
    return _compress_dict(data, depth=0)


def _compress_dict(obj: Any, depth: int) -> Any:
    """Recursive helper – depth-limited to guard against pathological nesting."""
    if depth > 3:
        return obj
    if isinstance(obj, dict):
        out: dict[str, Any] = {}
        for k, v in obj.items():
            if isinstance(v, list) and k in _HEAVY_ARRAY_KEYS:
                original_len = len(v)
                truncated = v[:_MAX_ARRAY_ITEMS]
                out[k] = [_compress_dict(item, depth + 1) for item in truncated]
                if original_len > _MAX_ARRAY_ITEMS:
                    out[f"__{k}_total__"] = original_len
                    out[f"__{k}_shown__"] = len(truncated)
            else:
                out[k] = _compress_dict(v, depth + 1)
        return out
    if isinstance(obj, list):
        return [_compress_dict(item, depth + 1) for item in obj]
    return obj


def make_ultra_compact_tool_summary(tool_name: str, content_json: str) -> str:
    """
    Reduce a stored tool result to a single-line key-fact summary string.

    Used when a tool message is too old to warrant keeping even its compressed
    JSON – we replace it with a ≤80 char plain-text line so the model retains
    awareness that the call happened without paying tokens for the payload.

    Example output:
        "[run_backtest] 112 trades, win_rate=58.3%, pnl=+4.21%, bal=$1042.10"
    """
    try:
        data = json.loads(content_json)
    except (json.JSONDecodeError, TypeError):
        return f"[{tool_name}] result available (summary omitted to save context)"

    def _get(*keys: str) -> Any:
        """Safe nested-key lookup across common result shapes."""
        for k in keys:
            if isinstance(data, dict) and k in data:
                return data[k]
            # Try one level down (e.g. data["summary"]["win_rate"])
            for sub in data.values() if isinstance(data, dict) else []:
                if isinstance(sub, dict) and k in sub:
                    return sub[k]
        return None

    # -- Backtest results ---------------------------------------------------
    if tool_name == "run_backtest":
        trades   = _get("total_trades")
        wr       = _get("win_rate")
        pnl      = _get("total_pnl_pct")
        bal      = _get("final_balance")
        parts = [f"[run_backtest]"]
        if trades is not None: parts.append(f"{trades} trades")
        if wr     is not None: parts.append(f"win_rate={wr:.1f}%")
        if pnl    is not None: parts.append(f"pnl={pnl:+.2f}%")
        if bal    is not None: parts.append(f"bal=${bal:.2f}")
        return ", ".join(parts) if len(parts) > 1 else f"[run_backtest] completed"

    # -- Strategy list -------------------------------------------------------
    if tool_name in ("get_strategies", "get_backtest_strategies"):
        total = _get("total") or _get("count")
        return f"[{tool_name}] {total or '?'} strategies returned"

    # -- Models --------------------------------------------------------------
    if tool_name in ("get_models", "get_model_detail"):
        total = _get("total") or _get("model_name")
        return f"[{tool_name}] {total or 'result'} returned"

    # -- Sentiment -----------------------------------------------------------
    if tool_name in ("get_sentiment_results", "run_sentiment"):
        coin  = _get("coin")
        score = _get("mean_sentiment") or _get("overall_score")
        posts = _get("total_posts")
        parts = [f"[{tool_name}]"]
        if coin:  parts.append(f"coin={coin}")
        if score is not None: parts.append(f"sentiment={score:.3f}")
        if posts is not None: parts.append(f"{posts} posts")
        return ", ".join(parts)

    # -- OHLCV ---------------------------------------------------------------
    if tool_name == "get_ohlcv":
        sym   = _get("symbol")
        rows  = _get("total_rows")
        close = _get("close")
        return f"[get_ohlcv] {sym or '?'}: {rows or '?'} candles, close={close}"

    # Generic fallback
    keys = list(data.keys())[:5] if isinstance(data, dict) else []
    return f"[{tool_name}] keys={keys}"


# ===========================================================================
# Deduplication: remove consecutive identical tool results
# ===========================================================================

def deduplicate_tool_results(
    history: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Remove tool messages whose (name, content) pair is an exact duplicate of an
    earlier tool message in the same session.

    In a typical backtest loop the model may call get_backtest_strategies twice
    in a long session. Keeping both copies doubles the token cost for zero
    information gain.

    The system message (index 0) and all non-tool messages are never touched.
    """
    if not history:
        return history

    seen_tool_signatures: set[str] = set()
    result: list[dict[str, Any]] = []

    for msg in history:
        if msg.get("role") == "tool":
            # Signature = tool name + first 200 chars of content (fast proxy)
            sig = f"{msg.get('name','')}::{str(msg.get('content',''))[:200]}"
            if sig in seen_tool_signatures:
                logger.debug(
                    "deduplicate_tool_results | removed duplicate tool msg: %s",
                    msg.get("name"),
                )
                continue
            seen_tool_signatures.add(sig)
        result.append(msg)

    return result


# ===========================================================================
# History trimming (structural – drops whole messages)
# ===========================================================================

def trim_history(
    history: list[dict[str, Any]],
    budget: int = TOKEN_BUDGET,
) -> list[dict[str, Any]]:
    """
    Trim an OpenAI-format messages list so its estimated token count fits
    within *budget*.

    Algorithm (priority order)
    --------------------------
    1. Always preserve history[0] (system prompt).
    2. Deduplicate identical tool results (free savings, no info loss).
    3. If within budget after dedup → return immediately.
    4. Replace stale tool messages with ultra-compact one-line summaries.
    5. Drop oldest non-system messages until within budget.
    6. Preserve mandatory tail (_MIN_RECENT_MESSAGES) unconditionally.
    7. Last resort: hard-truncate the content of the single largest tool msg.

    Does NOT mutate the input list.
    """
    if not history:
        return history

    # Step 0: dedup (no token cost, may free significant space)
    history = deduplicate_tool_results(history)

    current_tokens = estimate_messages_tokens(history)
    if current_tokens <= budget:
        return history

    logger.info(
        "trim_history | tokens=%d > budget=%d | len=%d",
        current_tokens, budget, len(history),
    )

    system_msg = history[0]
    non_system = list(history[1:])

    # Step 1: Replace stale (old) tool messages with compact summaries.
    # "Stale" = not in the last _STALE_TOOL_ROUNDS * 3 messages.
    stale_cutoff = max(0, len(non_system) - _STALE_TOOL_ROUNDS * 3)
    for i, msg in enumerate(non_system[:stale_cutoff]):
        if msg.get("role") == "tool":
            compact = make_ultra_compact_tool_summary(
                msg.get("name", "tool"),
                msg.get("content", "{}"),
            )
            non_system[i] = {**msg, "content": compact}

    after_compact = [system_msg] + non_system
    current_tokens = estimate_messages_tokens(after_compact)
    if current_tokens <= budget:
        logger.info(
            "trim_history | resolved by compacting stale tool msgs | tokens=%d",
            current_tokens,
        )
        return after_compact

    # Step 2: Drop from oldest end, keeping mandatory tail.
    mandatory_start = max(0, len(non_system) - _MIN_RECENT_MESSAGES)
    mandatory_tail = non_system[mandatory_start:]
    trimmable = non_system[:mandatory_start]

    while trimmable:
        candidate = [system_msg] + trimmable + mandatory_tail
        if estimate_messages_tokens(candidate) <= budget:
            break
        dropped = trimmable.pop(0)
        logger.debug(
            "trim_history | dropped msg role=%s len=%d",
            dropped.get("role"),
            len(str(dropped.get("content") or "")),
        )

    trimmed = [system_msg] + trimmable + mandatory_tail
    after_tokens = estimate_messages_tokens(trimmed)
    logger.info(
        "trim_history | after structural trim | tokens=%d | removed=%d msgs",
        after_tokens, len(history) - len(trimmed),
    )

    # Step 3: Last-resort hard content truncation on the largest tool message.
    if after_tokens > budget:
        trimmed = _truncate_largest_tool_message(trimmed, budget)

    return trimmed


def _truncate_largest_tool_message(
    history: list[dict[str, Any]],
    budget: int,
) -> list[dict[str, Any]]:
    """Hard-truncate the largest tool message content as a last resort."""
    largest_idx, largest_len = -1, 0
    for i, msg in enumerate(history):
        if msg.get("role") == "tool":
            content = msg.get("content") or ""
            if isinstance(content, str) and len(content) > largest_len:
                largest_len = len(content)
                largest_idx = i

    if largest_idx == -1:
        return history

    other_tokens = estimate_messages_tokens(
        [m for i, m in enumerate(history) if i != largest_idx]
    )
    remaining = budget - other_tokens
    max_chars = max(150, int(remaining * _CHARS_PER_TOKEN))

    new_history = list(history)
    original = new_history[largest_idx].get("content", "")
    if isinstance(original, str) and len(original) > max_chars:
        new_history[largest_idx] = {
            **new_history[largest_idx],
            "content": (
                original[:max_chars]
                + "\n...[truncated – payload too large for context]..."
            ),
        }
        logger.warning(
            "_truncate_largest_tool_message | truncated %d → %d chars",
            len(original), max_chars,
        )
    return new_history


# ===========================================================================
# Session-level summarisation (proactive, mutates _SESSION_STORE in place)
# ===========================================================================

def build_summary_message(history: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Build a compact role="user" summary message from a history list.

    The summary is built locally without an LLM call and covers:
    - Which tools were executed and their compact outcomes
    - The last user question and assistant answer (truncated to 400 chars each)

    This is injected at position [1] (right after the system prompt) to give
    the model context about what happened earlier without paying full token cost.
    """
    tool_summaries: list[str] = []
    last_user = ""
    last_assistant = ""

    for msg in history:
        role = msg.get("role")
        if role == "tool":
            name = msg.get("name", "tool")
            content = msg.get("content", "{}")
            tool_summaries.append(make_ultra_compact_tool_summary(name, content))
        elif role == "user":
            content = msg.get("content") or ""
            if isinstance(content, str) and content:
                last_user = content[-400:]
        elif role == "assistant":
            content = msg.get("content") or ""
            if isinstance(content, str) and content:
                last_assistant = content[-400:]

    parts = ["[PRIOR CONTEXT – older turns were compressed to save tokens]"]
    if tool_summaries:
        # Deduplicate while preserving order
        seen: set[str] = set()
        unique = [s for s in tool_summaries if not (s in seen or seen.add(s))]  # type: ignore[func-returns-value]
        parts.append("Tools used: " + " | ".join(unique))
    if last_user:
        parts.append(f"User asked: {last_user}")
    if last_assistant:
        parts.append(f"Assistant replied: {last_assistant}")

    return {"role": "user", "content": "\n".join(parts)}


def compress_session(
    session_store: dict[str, list[dict[str, Any]]],
    session_id: str,
    budget: int = SOFT_COMPRESSION_THRESHOLD,
) -> None:
    """
    Proactively compress a session IN PLACE when it exceeds *budget* tokens.

    This is called by _append_message() after every write.  It ensures the
    stored history never grows uncontrollably between requests, which was the
    root cause of repeated 413 errors even after single-retry logic was added.

    Strategy
    --------
    1. Estimate current token usage.
    2. If within budget → no-op (fast path).
    3. Build a summary from all messages older than _MIN_RECENT_MESSAGES.
    4. Replace the old messages with: system_msg + summary_msg + recent_tail.
    5. Write the compressed list back to session_store[session_id].

    The user-visible history (GET /ai/history) is stored separately in a
    _HISTORY_STORE dict (see ai_service.py) and is NOT compressed, so the
    user always sees their full conversation.
    """
    history = session_store.get(session_id)
    if not history:
        return

    # First pass: dedup (cheap, always run)
    history = deduplicate_tool_results(history)
    session_store[session_id] = history

    current_tokens = estimate_messages_tokens(history)
    if current_tokens <= budget:
        return  # fast path – no compression needed

    logger.info(
        "compress_session | session=%s | tokens=%d > soft_threshold=%d | compressing",
        session_id, current_tokens, budget,
    )

    system_msg = history[0]
    non_system = history[1:]

    # Identify the "old" portion to summarise
    recent_cutoff = max(0, len(non_system) - _MIN_RECENT_MESSAGES)
    old_messages = non_system[:recent_cutoff]
    recent_tail = non_system[recent_cutoff:]

    if not old_messages:
        # Nothing to summarise – all messages are "recent".
        # Force-trim the tail to fit.
        session_store[session_id] = trim_history(history, budget=budget)
        return

    # Build a summary of the old messages
    summary_msg = build_summary_message(old_messages)

    # Check if any existing summary message is already at index 1 –
    # if so, merge with it rather than stacking summaries.
    if (
        recent_tail
        and recent_tail[0].get("role") == "user"
        and recent_tail[0].get("content", "").startswith("[PRIOR CONTEXT")
    ):
        # Already has a summary; merge
        existing_summary = recent_tail[0]["content"]
        merged_content = summary_msg["content"] + "\n\n" + existing_summary
        summary_msg = {"role": "user", "content": merged_content[-1200:]}
        recent_tail = recent_tail[1:]

    compressed = [system_msg, summary_msg] + recent_tail
    after_tokens = estimate_messages_tokens(compressed)

    logger.info(
        "compress_session | session=%s | before=%d | after=%d tokens | "
        "summarised %d old messages",
        session_id, current_tokens, after_tokens, len(old_messages),
    )

    # If still over budget after summary injection, do a structural trim
    if after_tokens > budget:
        compressed = trim_history(compressed, budget=budget)

    session_store[session_id] = compressed


# ===========================================================================
# Emergency compression (used inside _call_groq_with_budget 413 retry path)
# ===========================================================================

def emergency_compress(
    messages: list[dict[str, Any]],
    budget: int = EMERGENCY_TOKEN_BUDGET,
) -> list[dict[str, Any]]:
    """
    Maximally compress a messages list to fit within *budget*.

    This is called during the 413 retry path to ensure the retry payload will
    definitely fit, even if it means keeping very little history.

    Unlike compress_session() this does NOT mutate the session store – it
    returns a new (disposable) messages list for the retry call only.
    The session store is separately updated via compress_session().

    Steps
    -----
    1. Keep system prompt.
    2. Build a summary of everything.
    3. Keep only the last 2 messages (most recent user + assistant).
    4. If still over budget, drop the summary and keep only last 1 message.
    """
    if not messages:
        return messages

    system_msg = messages[0]
    non_system = messages[1:]

    summary_msg = build_summary_message(non_system)

    # Try: system + summary + last 3 messages
    for tail_size in (3, 2, 1):
        recent = non_system[-tail_size:] if len(non_system) >= tail_size else non_system
        candidate = [system_msg, summary_msg] + recent
        if estimate_messages_tokens(candidate) <= budget:
            logger.info(
                "emergency_compress | fit with tail=%d | tokens=%d",
                tail_size, estimate_messages_tokens(candidate),
            )
            return candidate

    # Absolute minimum: system + summary only
    minimal = [system_msg, summary_msg]
    if estimate_messages_tokens(minimal) <= budget:
        return minimal

    # Nuclear option: system + truncated summary
    max_summary_chars = int(budget * _CHARS_PER_TOKEN * 0.8)
    truncated_content = summary_msg["content"][:max_summary_chars]
    return [system_msg, {"role": "user", "content": truncated_content}]